### ISSUE TITLE
It is not running in Intellij IDE and jdk 11.

### ISSUE THREAD

**Issue by Chuntianhong** [HanSolo/tilesfxdemo#3]
How are you?
Thanks for sharing the great project.
I love this and I want to use this library.
But I download project and tried to compile, but it occurs the exception and never run.
I can't see the running app.

Always get following exception. Would you check it please and give me hint?

> Task :Overview.main()
Exception in Application start method
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:404)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.tools.Helper.readProperties(Helper.java:873)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.tools.Helper.getHiresCountryPaths(Helper.java:847)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.skins.CountryTileSkin.initGraphics(CountryTileSkin.java:92)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.skins.TileSkin.<init>(TileSkin.java:131)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.skins.CountryTileSkin.<init>(CountryTileSkin.java:74)
	at eu.hansolo.tilesfx/eu.hansolo.tilesfx.Tile.createDefaultSkin(Tile.java:6105)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.access$3400(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2477)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by HanSolo** [comment]
Not sure how you try to start the demo but if you go to the gradle panel in IntelliJ, choose "tilesfxdemo" -> "Tasks" -> "other" -> "Demo" and double click it it should start. I've tested it on my machine and it works totally fine with JDK11 in IntelliJ 2020.2
![TilesFX 2020-09-08 13-44-59](https://user-images.githubusercontent.com/62843/92472406-b11ebb80-f1d9-11ea-8133-991284a4ac66.jpg)

**Comment by Chuntianhong** [comment]
Thanks for your answer.
I need to install JDK 11?

**Comment by MXHanner** [comment]
I use JDK11 and JavaFX11, and I get the same exception when I run the project both in Eclipse and IDEA. Could you please give me a hint? Is there something wrong with my configuration?
